### ISSUE TITLE
Implementar generación dump de analytics en CSV

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#138]
Implementar un path de descarga de analytics en CSV diario como:

`apis.datos.gob.ar/management/analytics/{api_id o api_name}/analytics_{date}.csv`

Revisar si conviene guardarlo zipeado y que sea:

`apis.datos.gob.ar/management/analytics/{api_id o api_name}/analytics_{date}.zip`

**Comment by abenassi** [comment]
Agregar autenticación para poder descargar los dumps de analtyics.

**Comment by alejandrosobko** [comment]
@abenassi hecho acá https://github.com/datosgobar/api-gateway/commit/474035581a2a607e9661ec42e846114501c56d7d

**Comment by abenassi** [comment]
@alejandrosobko a esto le faltaría documentarlo en el repo para estar listo, lo devuelvo a in progress

**Comment by alejandrosobko** [comment]
@abenassi El feature ya llegó a stage. La url correcta es http://apis-stg.datos.gob.ar/management/api/analytics/series-tiempo-stg/analytics_2018-10-31.csv.

La doc está acá [generación de analytics](https://github.com/datosgobar/api-gateway/blob/master/docs/django.md#generaci%C3%B3n-de-csv-de-analytics).
