### ISSUE TITLE
Investigar consistencia entre Google Analytics y dump API gw

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#148]
Chequear también que API gw permite configurar id de Google Analytics en la UI de la aplicación.

**Comment by poligarcia** [comment]
@alejandrosobko podrás agregar por favor una descripción con lo que descubrimos ayer?

**Comment by alejandrosobko** [comment]
Api Management usa _Google Analytics Collection_. Según [su documentación](https://developers.google.com/analytics/devguides/collection/other/limits-quotas) GA recibe hasta un máximo de 500 requests por _session_ (no encontré dónde definen cuánto dura), el resto los tira.
Lo que hice [acá](7904b225708472ad3ab84bc0a3f4a32d17363d3b) fue enviar el parámetro `sc` para indicar que cada request inicia una nueva _session_. No encontré advertencias sobre crear muchas sesiones así que asumo que no vamos a tener problemas.
De esta forma, cada request crea una nueva sesión y ya deberíamos recibir todo.

Más info sobre parámetros [acá](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters).
