### ISSUE TITLE
Investigar cómo cargar los analytics históricos a  GA

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#154]

**Comment by alejandrosobko** [comment]
Estuve investigando sobre el tema y no podemos modificar la fecha en que se hace el request por los siguientes motivos:
+ Google Analytics no nos permite enviar un parámetro para ser usado como _fecha en que se hizo el request_, por lo tanto de esta forma no podemos indicarle la antiguedad de un _hit_.
+ Curl no tiene un parámetro para indicar la fecha en que se está haciendo el request, por lo tanto de esta forma tampoco podemos indicarle a Google analytics cuándo le estamos pegando.

Si es sumamente necesario enviar todo el histórico a GA, podemos armar un script y que le pegue enviando todos los Query. Esto haría que tengamos la misma cantidad, pero todos en un mismo día.
