### ISSUE TITLE
Spike: diseño de implementación de analytics con Elastic + Kibana

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#157]
**Contexto**

Como administrador de una API usando el servicio de API Gateway quiero:

+ poder acceder a dashboards analíticos pre-armados que muestran indicadores de la API
+ armar mis propios dashboards

**Propuesta**

Elaborar una propuesta de integración de Kibana en API Gateway para explotación de analytics de c/api.

+ Debe preservar autenticación
+ Debe poder accederse desde el Django de API mgmt (al menos de una manera simple, como un link)
+ Debe ser solo para super usuarios

**Comment by lucaslavandeira** [comment]
Estructura tentativa del índice de analytics
```{
  "queries": {
    "mappings": {
      "doc": {
        "properties": {
          "api_data": {
            "type": "keyword"
          },
          "host": {
            "type": "keyword"
          },
          "id": {
            "type": "keyword"
          },
          "ip_address": {
            "type": "ip"
          },
          "params": {
            "type": "object",
            "enabled": false
          },
          "querystring": {
            "type": "text"
          },
          "request_method": {
            "type": "keyword"
          },
          "request_time": {
            "type": "float"
          },
          "start_time": {
            "type": "date"
          },
          "status_code": {
            "type": "keyword"
          },
          "token": {
            "type": "keyword"
          },
          "uri": {
            "type": "keyword"
          },
          "user_agent": {
            "type": "text"
          },
          "x_source": {
            "type": "keyword"
          }
        }
      }
    }
  }
}
```

**Comment by lucaslavandeira** [comment]
- El setup de Kibana a través de Kong es simple, se debe configurar usando el parámetro `server.basePath` igual que la uri configurada en Kong.
- La carga de datos también es sencilla, un simple script que todos los días se descargue los últimos analytics y lo indexe en el cluster de ES configurado en la misma instancia.

Sobre autenticación tenemos tres opciones:
- Plugin JWT de Kong con consumers, que ya está siendo usado. Contra: configurar el uso del header en un browser es molesto y para nada user-friendly
- Autenticación a través de nginx de kong: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ Tendríamos una contraseña global para todos los super usuarios que quieran usar el servicio.
Contras: bastante hacky de implementar, y puede ser sometido a ataques de fuerza bruta
- Limitar acceso a un rango limitado de IPs. Solución más limpia y simple. Contra: no nos permite poder acceder en donde querramos, si la IP de algún usuario cambia se le debe permitir acceder manualmente
