### ISSUE TITLE
Chequear significado de los hits 204 y hasta donde llegan en analytics

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#158]

**Comment by alejandrosobko** [comment]
Cada request que sale del explorer, envía un _custom header_ "X-Source". Entonces, primero se realiza un request de tipo _OPTIONS_ para validar este header. Cuándo el server nos responde con un _ok_ (204), recién ahí enviamos nuestro request original (GET, POST, o el que sea).
Este request (OPTIONS) lo recibe el server, y lo trata como cualquiera; es decir, genera un objeto Query y le pega a Google Analytics. Luego, lo mismo con el request original.
Entonces, todo lo que salga del explorer va a duplicar la información. Esto no es un bug, es un comportamiento normal ya que estamos enviando headers que no son parte del estándar.
Desde Google Analytics no tenemos forma de especificar o filtrar por status_code, por lo tanto no podemos saber qué información fue hecha por un OPTIONS y cuál no.

La solución que propongo es, cuando el server recibe un OPTIONS, no generar un objeto Query ni pegarle a Google Analytics ya que no aporta nada y la misma información va a ser trackeada con el request siguiente; pero loguear en algún lado que recibimos ese request, para que por algún motivo podamos encontrarlo si necesitamos información.
