### ISSUE TITLE
Configurar Elastic + Kibana y deployar a stg

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#160]
+ Optamos por la autenticación con contraseña global.
+ Faltaría incorporar al script de deploy todas las dependencias que haga falta y deployar a stg, donde Fede lo testearía.
+ Separar en dos índices la info analytcs para el usuario final (sin los OPTIONS) y para debugging posible (con todo incluido o con la diferencia)

**Comment by lucaslavandeira** [comment]
Mejor trackeado en dos issues separados de datosgobar/api-gateway-deploy
