### ISSUE TITLE
Implementar zipeado de analytics CSV

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#174]
Se considera un período de tiempo "current" y uno "histórico". El histórico se descarga zipeado y el "current" como CSV sin zipear.

**Comment by alejandrosobko** [comment]
Cómo sería la definición de la tarea? Qué archivos zippeo? Los anteriores a 1 año, 2?

**Comment by abenassi** [comment]
@alejandrosobko sí, la idea sería hacer un zip por año que permita hacer:

+ /analytics_2018.zip
+ /analytics_2019.zip

para todos los años, y 

+ /analytics_2018-11-01.csv
+ /analytics_2018-11-02.csv
+ /analytics_2018-11-03.csv
+ /analytics_2018-11-04.csv

sólo para los últimos 365 días disponibles. Cada día agregarías uno de esos CSVs al zipeado del año que le corresponde y lo borrarías de API mgmt (si hay por lo menos 365 días ya en CSV, sino sólo agrega el CSV al ZIP pero no borra hasta que haya 365 o más).
