### ISSUE TITLE
Armar un dashboard sencillo de kibana en prod con algunas consultas básicas a analytics de la API

### ISSUE THREAD

**Issue by abenassi** [datosgobar/api-gateway#193]
+ hits tiempo real
+ hits mensuales acumulados (históricos)
+ usuarios únicos mensuales
+ usuarios únicos acumulados (históricos)

**Comment by alejandrosobko** [comment]
Se implementaron los últimos 3 items pedidos como visualizaciones de un dashboard.
Sobre "hits tiempo real": Se observan desde el menú "Discover" o desde cualquier visualización. El tiempo de refresh es ajustable.
