### ISSUE TITLE
Mas soporte para Documentacion

### ISSUE THREAD

**Issue by lalo73** [datosgobar/api-gateway#86]
Hoy la aplicacion soporta un campo para mostrar la documentacion segun `swagger`.

Agregar soporte para poner una URL a ReadTheDocs.

Definir:
- Se pone un link/boton en la pagina de swagger o se reemplaza swagger con un redirect.

En caso del redirect, se debe notificar al usuario y debe ser un 302.

**Comment by lalo73** [comment]
@abenassi @pilimayora habiamos quedado en hacer el redirect, no?

**Comment by abenassi** [comment]
Si si, en efecto
